-- ============================================================================
-- MG3D — schema de e-commerce (idempotente: pode rodar várias vezes)
-- ============================================================================
-- Ordem de execução: tabelas -> colunas novas -> funções -> RLS -> índices.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tabelas
-- ----------------------------------------------------------------------------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  color text,
  badge text default '',
  image text not null,
  description text default '',
  details text default '',
  material text not null default 'PLA',
  dimensions text default '',
  production text default '',
  colors text default '',
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  allow_preorder boolean not null default true,
  photo_visible boolean not null default true,
  admin_file_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  phone text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete set null,
  status text not null default 'pending',
  total integer not null default 0 check (total >= 0),
  payment_provider text,
  payment_status text not null default 'unpaid',
  payment_session_id text,
  payment_intent_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2. Colunas adicionadas depois da primeira versão do schema
--    (o código de pagamento e de notificação já dependia delas)
-- ----------------------------------------------------------------------------
alter table public.customers add column if not exists phone text;
alter table public.orders add column if not exists payment_provider text;
alter table public.orders add column if not exists payment_status text not null default 'unpaid';
alter table public.orders add column if not exists payment_session_id text;
alter table public.orders add column if not exists payment_intent_id text;

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('awaiting_payment', 'pending', 'processing', 'shipped', 'delivered', 'cancelled'));

alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders add constraint orders_payment_status_check
  check (payment_status in ('unpaid', 'paid', 'refunded', 'failed'));

-- ----------------------------------------------------------------------------
-- 3. Funções
-- ----------------------------------------------------------------------------

-- Único lugar do banco que define quem é administrador.
-- Precisa ser o mesmo e-mail de NEXT_PUBLIC_ADMIN_EMAIL na aplicação.
create or replace function public.is_mg3d_admin()
returns boolean
language sql
stable
as $$
  select coalesce(lower(auth.jwt() ->> 'email') = 'maicntsuda@gmail.com', false);
$$;

-- Baixa de estoque atômica (usada pelo webhook do Stripe).
create or replace function public.decrement_product_stock(p_product_id bigint, p_quantity integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  remaining integer;
begin
  update public.products
     set stock_quantity = greatest(0, stock_quantity - greatest(0, p_quantity)),
         updated_at = now()
   where id = p_product_id
  returning stock_quantity into remaining;
  return remaining;
end;
$$;

revoke all on function public.decrement_product_stock(bigint, integer) from public, anon, authenticated;
grant execute on function public.decrement_product_stock(bigint, integer) to service_role;

-- updated_at automático
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at before update on public.products
  for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at before update on public.orders
  for each row execute function public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- 4. Row Level Security
-- ----------------------------------------------------------------------------
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.newsletter_subscribers enable row level security;

drop policy if exists public_read_active_products on public.products;
create policy public_read_active_products on public.products
  for select using (active = true or public.is_mg3d_admin());

drop policy if exists admin_manage_products on public.products;
create policy admin_manage_products on public.products
  for all using (public.is_mg3d_admin()) with check (public.is_mg3d_admin());

drop policy if exists users_manage_customer on public.customers;
create policy users_manage_customer on public.customers
  for all using (auth.uid() = id or public.is_mg3d_admin())
  with check (auth.uid() = id or public.is_mg3d_admin());

drop policy if exists users_read_orders on public.orders;
create policy users_read_orders on public.orders
  for select using (auth.uid() = customer_id or public.is_mg3d_admin());

-- IMPORTANTE: pedidos passaram a ser criados apenas pelo servidor
-- (/api/stripe/checkout, com a service role key), que calcula o total a partir
-- dos preços do banco. Sem essas policies o navegador não consegue mais
-- inventar um pedido de ¥1.
drop policy if exists users_create_orders on public.orders;
drop policy if exists users_create_order_items on public.order_items;

drop policy if exists admin_update_orders on public.orders;
create policy admin_update_orders on public.orders
  for update using (public.is_mg3d_admin()) with check (public.is_mg3d_admin());

drop policy if exists users_read_order_items on public.order_items;
create policy users_read_order_items on public.order_items
  for select using (
    exists (
      select 1 from public.orders o
       where o.id = order_id
         and (o.customer_id = auth.uid() or public.is_mg3d_admin())
    )
  );

drop policy if exists admin_read_newsletter on public.newsletter_subscribers;
create policy admin_read_newsletter on public.newsletter_subscribers
  for select using (public.is_mg3d_admin());

-- ----------------------------------------------------------------------------
-- 5. Índices
-- ----------------------------------------------------------------------------
create index if not exists products_active_idx on public.products(active);
create index if not exists products_slug_idx on public.products(slug);
create index if not exists orders_customer_idx on public.orders(customer_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
