-- MG3D ecommerce schema
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  color text,
  badge text default '',
  image text not null,
  description text default '',
  details text default '',
  material text not null default 'PLA',
  dimensions text default '',
  production text default '',
  colors text default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete set null,
  status text not null default 'pending',
  total integer not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price integer not null,
  quantity integer not null check (quantity > 0)
);

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists public_read_active_products on public.products;
create policy public_read_active_products on public.products for select using (active = true or (auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists admin_manage_products on public.products;
create policy admin_manage_products on public.products for all using ((auth.jwt()->>'email') = 'maicntsuda@gmail.com') with check ((auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists users_manage_customer on public.customers;
create policy users_manage_customer on public.customers for all using (auth.uid() = id or (auth.jwt()->>'email') = 'maicntsuda@gmail.com') with check (auth.uid() = id or (auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists users_read_orders on public.orders;
create policy users_read_orders on public.orders for select using (auth.uid() = customer_id or (auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists users_create_orders on public.orders;
create policy users_create_orders on public.orders for insert with check (auth.uid() = customer_id);

drop policy if exists users_read_order_items on public.order_items;
create policy users_read_order_items on public.order_items for select using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or (auth.jwt()->>'email') = 'maicntsuda@gmail.com')));

create index if not exists products_active_idx on public.products(active);
create index if not exists orders_customer_idx on public.orders(customer_id);
