-- MG3D ecommerce schema
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  color text,
  badge text default '',
  image text not null,
  description text default '',
  details text default '',
  material text not null default 'PLA',
  dimensions text default '',
  production text default '',
  colors text default '',
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  allow_preorder boolean not null default true,
  photo_visible boolean not null default true,
  admin_file_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text,
  phone text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete set null,
  status text not null default 'pending',
  total integer not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price integer not null,
  quantity integer not null check (quantity > 0)
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.newsletter_subscribers enable row level security;
-- No public policy is created for newsletter_subscribers. Only server-side service role access is allowed.

drop policy if exists public_read_active_products on public.products;
create policy public_read_active_products on public.products for select using (active = true or (auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists admin_manage_products on public.products;
create policy admin_manage_products on public.products for all using ((auth.jwt()->>'email') = 'maicntsuda@gmail.com') with check ((auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists users_manage_customer on public.customers;
create policy users_manage_customer on public.customers for all using (auth.uid() = id or (auth.jwt()->>'email') = 'maicntsuda@gmail.com') with check (auth.uid() = id or (auth.jwt()->>'email') = 'maicntsuda@gmail.com');

drop policy if exists users_read_orders on public.orders;
create policy users_read_orders on public.orders for select using (auth.uid() = customer_id or (auth.jwt()->>'email') = 'maicntsuda@gmail.com');

-- Pedidos são criados somente pela API server-side, que valida preços e estoque
-- usando a service role. Clientes autenticados podem consultar apenas os próprios pedidos.
drop policy if exists users_create_orders on public.orders;

drop policy if exists users_read_order_items on public.order_items;
create policy users_read_order_items on public.order_items for select using (exists (select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or (auth.jwt()->>'email') = 'maicntsuda@gmail.com')));

create index if not exists products_active_idx on public.products(active);
create index if not exists orders_customer_idx on public.orders(customer_id);


-- A API de pedidos insere os itens após consultar os dados canônicos do catálogo.
drop policy if exists users_create_order_items on public.order_items;

-- Compatibilidade para bancos criados antes da inclusão do telefone.
alter table public.customers add column if not exists phone text;
