export const products = [
  { id: 1, slug: 'vaso-orbital', name: 'Vaso Orbital', category: 'Casa', price: 1490, color: 'Tangerina', badge: 'Mais vendido', image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=90', desc: 'Geometria orgânica para plantas que pedem destaque.', details: 'Uma peça escultural com presença leve, criada para transformar plantas e pequenos cantos em pontos de interesse.', material: 'PLA', dimensions: 'Ø 18 × 20 cm', production: '3 a 5 dias úteis', colors: 'Tangerina, areia e preto' },
  { id: 2, slug: 'luminaria-halo', name: 'Luminária Halo', category: 'Luz', price: 2980, color: 'Areia', badge: 'Novo', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=90', desc: 'Luz suave, sombra escultural e presença na medida.', details: 'Um ponto de luz acolhedor que desenha sombras e cria atmosfera para leituras, conversas e pausas.', material: 'PLA', dimensions: 'Ø 24 × 28 cm', production: '5 a 7 dias úteis', colors: 'Areia, branco e azul' },
  { id: 3, slug: 'suporte-arc', name: 'Suporte Arc', category: 'Organização', price: 890, color: 'Preto', badge: '', image: 'https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&w=1200&q=90', desc: 'Seu fone sempre no lugar. Design limpo, mesa leve.', details: 'Um suporte compacto para organizar seus fones e manter a área de trabalho livre de excessos.', material: 'PETG', dimensions: '12 × 10 × 14 cm', production: '2 a 4 dias úteis', colors: 'Preto, azul e branco' },
  { id: 4, slug: 'bandeja-duna', name: 'Bandeja Duna', category: 'Casa', price: 1190, color: 'Terracota', badge: '', image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1200&q=90', desc: 'Uma peça tátil para chaves, joias e pequenos rituais.', details: 'Superfície inspirada em paisagens naturais para reunir objetos essenciais no hall, quarto ou escritório.', material: 'PLA', dimensions: '24 × 16 × 3 cm', production: '3 a 5 dias úteis', colors: 'Terracota, areia e oliva' },
  { id: 5, slug: 'vaso-nexo', name: 'Vaso Nexo', category: 'Casa', price: 1790, color: 'Oliva', badge: 'Edição limitada', image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1200&q=90', desc: 'Volume e textura que transformam qualquer canto.', details: 'Volumes conectados e textura marcada para plantas de médio porte e composições mais expressivas.', material: 'PLA', dimensions: 'Ø 20 × 24 cm', production: '4 a 6 dias úteis', colors: 'Oliva, azul e terracota' },
  { id: 6, slug: 'organizador-grid', name: 'Organizador Grid', category: 'Organização', price: 990, color: 'Cinza', badge: '', image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=90', desc: 'Pequenas formas, grandes possibilidades de organização.', details: 'Módulos versáteis para canetas, cabos, acessórios e tudo que merece um lugar definido.', material: 'TPU', dimensions: '18 × 12 × 8 cm', production: '2 a 4 dias úteis', colors: 'Cinza, preto e azul' },
]

export const categories = ['Todos', 'Casa', 'Luz', 'Organização']
export const formatJPY = value => `¥${value.toLocaleString('ja-JP')}`
