export const products = [
  { id: 1, slug: 'vaso-orbital', name: 'Vaso Orbital', category: 'Casa', price: 1490, stock_quantity: 0, allow_preorder: true, photo_visible: true, admin_file_url: '', color: 'Tangerina', badge: 'Mais vendido', image: 'https://res.cloudinary.com/dz5n4ul6j/image/upload/f_auto,q_auto,w_1200/v1788302531/vaso-orbital.jpg', desc: 'Geometria orgânica para plantas que pedem destaque.', details: 'Uma peça escultural com presença leve, criada para transformar plantas e pequenos cantos em pontos de interesse.', material: 'PLA', dimensions: 'Ø 18 × 20 cm', production: '3 a 5 dias úteis', colors: 'Tangerina, areia e preto' },
  { id: 2, slug: 'luminaria-halo', name: 'Luminária Halo', category: 'Luz', price: 2980, stock_quantity: 0, allow_preorder: true, photo_visible: true, admin_file_url: '', color: 'Areia', badge: 'Novo', image: 'https://res.cloudinary.com/dz5n4ul6j/image/upload/f_auto,q_auto,w_1200/v1788302533/luminaria-halo.jpg', desc: 'Luz suave, sombra escultural e presença na medida.', details: 'Um ponto de luz acolhedor que desenha sombras e cria atmosfera para leituras, conversas e pausas.', material: 'PLA', dimensions: 'Ø 24 × 28 cm', production: '5 a 7 dias úteis', colors: 'Areia, branco e azul' },
  { id: 5, slug: 'vaso-nexo', name: 'Vaso Nexo', category: 'Casa', price: 1790, stock_quantity: 0, allow_preorder: true, photo_visible: true, admin_file_url: '', color: 'Oliva', badge: 'Edição limitada', image: 'https://res.cloudinary.com/dz5n4ul6j/image/upload/f_auto,q_auto,w_1200/v1788302539/vaso-nexo.jpg', desc: 'Volume e textura que transformam qualquer canto.', details: 'Volumes conectados e textura marcada para plantas de médio porte e composições mais expressivas.', material: 'PLA', dimensions: 'Ø 20 × 24 cm', production: '4 a 6 dias úteis', colors: 'Oliva, azul e terracota' },
  { id: 7, slug: 'fantasma-coracao', name: 'Fantasma do Coração', category: 'Casa', price: 1500, stock_quantity: 0, allow_preorder: true, photo_visible: true, admin_file_url: '', color: 'Branco', badge: 'Halloween', image: '/fantasma-coracao.jpg', desc: 'Fantasma tricotado com um coração nas mãos.', details: 'Superfície tricotada, olhos pretos e coração vermelho. Pequeno o bastante para a estante, marcante o bastante para ser presente. Impresso peça por peça, sob encomenda.', material: 'PLA', dimensions: '56 × 58 × 60 mm (altura 60 mm)', production: '3 a 5 dias úteis', colors: 'Branco com coração vermelho' },
]

export const categories = ['Todos', 'Casa', 'Luz']
export const formatJPY = value => `¥${value.toLocaleString('ja-JP')}`
